<?php
/**
 * Copyright © Fiko Borizqy. All rights reserved.
 * See COPYING.txt for license details.
 */

 /**
<button class="scalable" type="button" id="<?= $block->getHtmlId() ?>" data-mage-init='{"testConnection":{
    "url": "<?= $block->escapeUrl($block->getAjaxUrl()) ?>",
    "elementId": "<?= $block->getHtmlId() ?>",
    "successText": "<?= $block->escapeHtmlAttr(__('Successful! Test again?')) ?>",
    "failedText": "<?= $block->escapeHtmlAttr(__('Connection failed! Test again?')) ?>",
    "fieldMapping": "<?= $block->getFieldMapping() ?>"}, "validation": {}}'>
    <span id="<?= $block->getHtmlId() ?>_result"><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
</button>
*/
?>

<div class="message message-warning">
<small>
    - <?= $escaper->escapeHtml(__('Current Counter Number of')) ?> <strong>Store View 1: 12</strong> <br/>
    - <?= $escaper->escapeHtml(__('Current Counter Number of')) ?> <strong>Store View 1: 23</strong> <br/>
</small>
</div>
<br/>
<button class="scalable" type="button" id="<?= $block->getHtmlId() ?>">
    <span id="<?= $block->getHtmlId() ?>_result"><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
</button>
<small>
    <br/><?= $escaper->escapeHtml(__('You can also reset manually the number by clicking this button.')) ?>
</small>
<script>
require([
    'jquery',
    'Magento_Ui/js/modal/confirm'
], function($, confirmation) {
    'use strict';

    $(document).on('click', '#<?= $block->getHtmlId() ?>', function() {
        confirmation({
            content: $.mage.__('Are you sure want to reset the counter number?'),
            actions: {
                confirm: function(){
                    $('#<?= $block->getHtmlId() ?>_result').text('Resetting...');
                    $('#<?= $block->getHtmlId() ?>').prop('disabled', true);
                    resetCounter();
                },
                // always: function(){
                //     $('#<?= $block->getHtmlId() ?>_result').text('<?= $block->escapeHtml($block->getButtonLabel()) ?>');
                //     $('#<?= $block->getHtmlId() ?>').prop('disabled', false);
                // }
            }
        });
    });

    const resetCounter = async () => {
        console.log('resetting...');
    };
});
</script>